server:
  port: 8090
spring:
  #main:
    #allow-bean-definition-overriding: true  
    #web-application-type: reactive
  config:
    import: configserver:http://localhost:8001
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
      - id: route-sentence
        uri: lb://spring-cloud-ms-sentence
        predicates:
        - Path=/apisentence/**
        filters:
        - RewritePath=/apisentence/(?<segment>.*),/sentence/$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
