spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mayerhorna/spring-cloud-config-server3
          search-paths: ConfigData
server:
  port: 8001         