server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: spring-cloud-ms-adjective
  config:
    import:
    - configserver:http://localhost:8001
  profiles:
    active:
    - adjective
